indragunawan_api_rate_limit:
    enabled: true
    throttle:
        default:
            limit: 10 # max attempts per period
            period: 3600 # in seconds
        sort: 'rate-limit-desc'
    cache: cache.rate_limiter

when@dev: 
    indragunawan_api_rate_limit:
        enabled: true
        throttle:
            default:
                limit: 1000 # max attempts per period
                period: 300 # in seconds
            sort: 'rate-limit-desc'
        cache: cache.rate_limiter


when@test: 
    indragunawan_api_rate_limit:
        enabled: true
        throttle:
            default:
                limit: 10000 # max attempts per period
                period: 300 # in seconds
            sort: 'rate-limit-desc'
        cache: cache.rate_limiter
