# Read the documentation: https://github.com/IndraGunawan/api-rate-limit-bundle/blob/master/Resources/doc/usage.md
indragunawan_api_rate_limit:
    enabled: true
    throttle:
        default:
            limit: 1000 # max attempts per period
            period: 60 # in seconds
        sort: 'rate-limit-desc'
