version: '3'

services:
    php:
        build: ./docker/php-fpm
        ports:
            - 9000:9000
        volumes:
            # - ./bin:/app/bin
            # - ./config:/app/config
            # - ./public:/app/public
            # - ./src:/app/src
            # - ./templates:/app/templates
            # - ./migrations:/app/migrations
            # - ./.env:/app/.env
            # - ./composer.json:/app/composer.json
            # - ./composer.lock:/app/composer.lock
            # - ./symfony.lock:/app/symfony.lock
            # - ./ship_positions.json:/app/ship_positions.json
            # - ./vendor:/app/vendor
            - ./:/app
        depends_on:
            - elasticsearch
    nginx:
        build: ./docker/nginx
        ports:
            - 8000:80
        volumes:
            # - ./config:/app/config
            # - ./public:/app/public
            # - ./src:/app/src
            # - ./templates:/app/templates
            # - ./migrations:/app/migrations
            # - ./.env:/app/.env
            # - ./vendor:/app/vendor
            - ./:/app
        depends_on:
            - php
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
        environment:
            - cluster.name=marinetraffic
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # 512mo HEAP
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200
    kibana:
        image: docker.elastic.co/kibana/kibana:7.9.3
        environment:
            ELASTICSEARCH_URL: ${ELASTICSEARCH_HOST}
        depends_on:
            - elasticsearch
        ports:
            - 5601:5601
